language: perl
perl: 
   - "5.16"
   - "5.14"
   - "5.12"

install:
   - cpanm --quiet --notest Template
   - cpanm --quiet --notest Dancer
   - cpanm --quiet --notest Dancer::Plugin::SiteMap;
   - cpanm --quiet --notest Dancer::Plugin::DirectoryView;
   - cpanm --quiet --notest Dancer::Plugin::Auth::Htpasswd;
