language: perl
perl: 
   - "5.16"
   - "5.14"
   - "5.12"

install:
   - cpanm -v --notest --installdeps .

notifications:
   recipients:
      - stephan@syntaktischer-zucker.de
   email:
      on_success: always
      on_failure: always
