language: perl
perl: 
   - "5.16"
   - "5.14"
   - "5.12"

install:
   - cpanm -q -n Template
   - cpanm -q -n Dancer
   - cpanm -q -n Dancer::Plugin::SiteMap
   - cpanm -q -n Dancer::Plugin::DirectoryView
   - cpanm -q -n Dancer::Plugin::Auth::Htpasswd
   - cpanm -q -n DBD::SQLite
   - cpanm -q -n File::Slurp
   - cpanm -q -n Crypt::SaltedHash
   - cpanm -q -n GD
   - cpanm -q -n GD::SecurityImage
   - cpanm -q -n Dancer::Plugin::Captcha::SecurityImage 



notifications:
   recipients:
      - stephan@syntaktischer-zucker.de
   email:
      on_success: always
      on_failure: always
