language: perl
perl: 
   - "5.16"
   - "5.14"
   - "5.12"

before_install:
   - sudo apt-get update
   - sudo apt-get install libgd-gd2-noxpm-perl
   - sudo apt-get install libgd2-noxpm-dev

install:
   - cpanm -q -n --skip-installed Template
   - cpanm -q -n --skip-installed Dancer
   - cpanm -q -n --skip-installed Dancer::Plugin::SiteMap
   - cpanm -q -n --skip-installed Dancer::Plugin::DirectoryView
   - cpanm -q -n --skip-installed Dancer::Plugin::Auth::Htpasswd
   - cpanm -q -n --skip-installed DBD::SQLite
   - cpanm -q -n --skip-installed File::Slurp
   - cpanm -q -n --skip-installed Crypt::SaltedHash
   - cpanm -q -n --skip-installed GD
   - cpanm -q -n --skip-installed GD::SecurityImage
   - cpanm -q -n --skip-installed Dancer::Plugin::Captcha::SecurityImage 
   - cpanm -q -n --skip-installed MIME::Lite
   - cpanm -q -n --skip-installed Net::SMTP
   - cpanm -q -n --skip-installed Net::SMTP::SSL
   - cpanm -q -n --skip-installed Net::SMTP::TLS

notifications:
   recipients:
      - stephan@syntaktischer-zucker.de
   email:
      on_success: always
      on_failure: always
